#%RAML 1.0
title: MobiForum
version: v1
baseUri: https://forum.mobi.com/api/{version}

/login:
  displayName: Authorization
  description: User need to get token for use the APIs
  post:
    queryParameters:
      email:
        required: true
      password:
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              {
                token: '...'
              }
        description: |
                      If the email address and password were entered correctly, then you will be given a token
      401:
        body:
          application/json:
            example:
              {
                message: 'Incorrect login or password'
              }
        description: |
                      Incorrect login or password

